[book]
authors = ["silinzhao"]
language = "en"
multilingual = false
src = "src"
title = "posts"

[output.html]
mathjax-support = true

[preprocessor.katex]
after = ["links"]
block-delimiter = { left = "$$", right = "$$" }
inline-delimiter = { left = "$", right = "$" }
copy-fonts = true
