#+TITLE:  OpenIdProject
#+OPTIONS: num:t
#+STARTUP: overview
#+AUTHOR:  Silin Zhao
* Project description
OpenIdProject is a open identification oriented  project, and based on block chain technology, social network Application. The key part is keeping all information which are relate to the owner, and tracing each those information back to when it occured. At the same time each propagation of those information will be cross
valided its exisence. This project is offical started now (Wed Aug  3 22:41:29 2022), but its desige has been start about 2018. I will start to describe  its content as following parting.

* What will be noted
** Was is valuable for us
Information is the only valuable matter, according to my personal opinion. irony, it's invisible.
From deep aspect, information is just one porperties of visible matter, one of  permutations of atoms.
so if people change the permutation, the corresponding information is lost.

According to the desige of the project, all information, which has been recorded with this application
should be able to be proofed with aspect to its exisence.

With the development of our social state, information access is getting more faster, but its purity and
ownership is not get guaranteed. But for a referencing, the purity and ownership of information should be so important as information itself. Those are valuable for us.

Here I list some information which can be as a example for our project.

*** Personal Information
In our society each of us should already has a identification, it can even be referenced to personal DNA serial. But now, our personal information is separated in different parts, health records, educational background, work experience... In the near further, I believe we should easily be able to  get known such information.

*** original work of copy right
creative ideas, digital artistic product, literary and artistic creative...
any of such things, should be labeled from its creator. All such records will be embeded into personal block chain with timestamp and ownership detail information. Copy right problem for  digital product can be solved with this project.

*** Smartcontract
basically, all smartcontract involved can be referenced also here, seeing later update

*** Records into block chain
Each records has unified hashtag. Even only one letter has been changed, its unified hashtag will be changed totally. This hashtag can only proof that, the original records has occured at its timestamp. Important, the recorded itself will NOT be embeded into block chain, only its hashtag. so if someone what to proof the exisence of one record, this person has to have the record.

*** sensitive information
from my understand, We don't need to hidden something. Our thinking, emotional feeling,  thoughts, amount of properties in bank... each of those should be unified labeled, and ownership protected in its owner personal chain.
*** ......

** Open philosophy
The best way to protect something is to let everyone knowning what it is.
Open, Open, Open is the core idea of this project, I don't need to hidden, of course, if I decide that I don't put something into the chain, and willing to take the risk for lossing it. It's totally my personal decision, but I courage myself to put all stuff into my chain.


** Building a personal identification oriented Databank
** Why and How to avoid information loss

* How records will be holded

* How records will be propagated

* How to deal with its drawback
* Info
* From Federated Learning to Decentralized Learning
