#+TITLE: 美人受难记
#+OPTIONS: num:nil
#+STARTUP: overview
* 前记
在一处风景秀丽，水草丰美的边垂小镇上生活着一位绝世美女，名叫鸟小飞
她姿态优美，皮肤细腻光泽，面如桃花，口齿流香。
此女子本是镇上一大家闺秀，奈何家道中落，被迫在此边缘之地自谋更生。
说是边垂之地，倒也不完全正确，若向另一个方向望去，也是一座大城，
大城和小镇的交通往来，倒使美女能从中能获取些许好处，美女自然也乐得其成。


说那镇上美女原本的大户人家中落后，家中长子晋羊担起重任，日夜奋起，期待有日能拾祖上的荣光，
而且按照祖辈的传承，晋公子已和鸟小姐共接连里，本该恩爱相处。
但是自从那次变故之后，当时两人都没有了那种想法，就先各自安好吧。
但是一日夫妻百日恩，两人藕段丝连，倒也没丢了体面。

时到今日，物欲横流，纷纷绕绕的世界人们都想用感官的享受来麻痹自己的神经，
祖辈的坚守不在被视为有意义和必须的了。这倒也能理解，顺着信息技术的发展，
任何人沟通的成本几乎不需要考虑了，人们提出了各种理论来规范人们的底线，描述人们的行为，
希望能更加清晰的靠近人的本性，追随天性。其中有一个很有诱惑力的观点，人们的性需求应该彻底解放。

这给了本身就很物质的世界更加开放了放纵的理由，过去大老爷们的妻妾成群现在有俩钱就可以享受一下。
晋大公子是见过祖上的阔气的，现在不但没有先祖的众花环绕，
连自己结发妻子鸟小飞也最多愿意和自己保持名义上联系，但是小飞从晋大公子这里掏钱倒是很熟练。
这在外人看来也是无可厚非的，毕竟名头挂你名下，你不用金钱维系一下，谁愿意傻傻的这样啊。

世界风云变换，近些年来城里经常来群财大器粗的公子哥，三五一群的，有时数十人一起，
他们早就看上了小飞的姿色，明里暗里又是送礼物，又是给小飞一套他们研究的很成熟的理论。
人应该为自己而活，封建礼教的那一套压抑人的天性。
要是小飞愿意放弃小镇生活，和他们到城里去，凭借小飞的条件，她可以过的相当的滋润。
小飞本身动摇了很久了，别人送的礼物是真金白银啊，
如果搬去城里，自己的就单单的往台上一站，就有非常多的人买票。
当然了，出卖色相，被人揩油那是少不了的。
但是在这个世界大家都在说性自由，小飞自己对这种需求也有着原始的冲动。
有什么不好，和城里公子哥谈恋爱既能有钱收，还能享受，多好的事。
毕竟现在婚前同居，出轨开房，私下堕胎到处都是，小飞这几十年听到的，偶尔去城里看到的数不胜数。
这就是目前的生活方法，成年人的世界赤裸裸的展现在小飞面前。

小飞也都三十好几了，自己知道自己要什么，法律也学了很多，家里时常来几位城里的公子哥，
有的当然也能在小飞家里过夜。小飞当然想和其中最有钱的一位还很漂亮的公子在一起。
小飞也知道，漂亮公子不会娶她，漂亮公子谁也不会娶，大家都单身的玩，自己开心就行。
而且儿子一大堆，女性朋友遍地的漂亮公子的确认为自己没必要结婚，人的自由应该获得认可。
他对苏格拉底的共产没兴趣，只想着共妻共子了。

而现实的世界就是绝大多数人也都认可这个理由，而人们不知道的是，之所以漂亮公子不愿意实现共产，
这恰恰就是他能实现共妻共子的财力支持，因为漂亮公子非常非常有钱。而没有掌握 大量钱财的普通人们，
大多都是跟着这个大哥，用性自由的理由，捡漏揩油。而在漂亮公子的朋友圈里倒也有些财力逐渐雄厚的后辈。
他们基本都同意目前的世界主流观点。 人们也研究过，对目前的观点做出过辩论，顺着人的自我实现，家庭的存在
的确在人达到某种生活水平后，便不是必须的。家庭是在个人能力不能实现自己的内心的诉求时最强有里的后援。
等到自己的确有能力完成自己的梦想时，维系两个人在一起的纽带就是单纯的情感。
人们愿意独处，或者和一个异性一起生活， 或者多个异性一起生活，或者同性，都是简简单单的出于内心的情感。
或许那就是人类终极生活方法吧。但是这一切都是需要如漂亮公子一般的雄厚的财力支持，从现实的角度来说，
漂亮公子有理由去实现这样的生活方式。也从实际的角度来说，没有如此财力的人也都向往这种生活，
可是实际操着起来，既有传统思想的羁绊，又得不到太多的好处，到头来，既觉得是被占了便宜，
又把自己本来可以好好积累财富的步伐给打乱了，但是心中对那美好生活一蹴而就的向往久久不能忘却。


小飞的处境还有一个大的不稳定，就是来自老相识晋大公子，晋大公子一直都抱着祖上的观念，
认为目前这些观点都是为了勾引女子上当才想出来的。女子就应该三从四德的服务家庭，大小老婆都应该和睦相处，
更何况他现在只有这一门房事。每次小飞在晋大公子过完夜，收了晋大公子的礼物后， 晋大公子都会大发脾气。
指责小飞收留不三不四的人过夜，行为应该检点些。小飞也把自己真实的想法说给了晋大公子。而且说的很决绝，
并且指出，她和晋大公子这先辈的指腹为婚的婚姻在现代社会是不相容的，每个人都有权利去选择自己的生活方式。
并且当方面的宣布和晋大公子离婚了。这事现在在小镇上都传开了，关键是小镇本就是晋大公子当家， 小飞希望走正常的司法程序解除婚姻根本不可能。而随着晋大公子越来越严厉的用祖宗家法来威胁小飞时，
凭借小飞对现代社会法制观点的理解，她并没有将家法的威胁放在心上。城里漂亮公子给小飞讲解过城里司法系统的
运作方式，基本的人权和法制保障在城里运行的非常良好。而这无疑更加让小飞觉得，比较起晋大公子控制的镇上的生活，城里现代文明制度下的生活更加能让小飞早日积累起自己的财富，实现自己的向往的生活方式。
但是小飞何尝不知道漂亮公子只是单纯的打自己肉体的注意，
对于自己过去不幸的婚姻生活，加上差不多就是单身的状态，何不趁着年轻为自己活一下。谁又能指责？
即便指责，也是从什么道德层面来的。在城里的司法体系观念中， 我小飞绝对有权利对自己的行为负责。

* 黑暗篇：：：

晋大公子不这么想，他在警告了很多次以后，终于忍不住了，在和一堆朋友喝了一顿酒后，
终于暗暗的下了决心，我怎么失去的，我就要怎么拿回来。恨的怕不要命的，漂亮公子再恨，可是他怕死啊，
我晋大公子只要不怕死，小飞就还是我的。什么城里的司法体系，在我镇上我说了算。
祖上的家法说了，妇人不守妇道，我有99种办法让她感受到切肤之痛。上千年对付这种情况的办法怎么可能会失效。
终于在一个风和日丽的下午，晋大公子带着打手卸掉了小飞院子的门，打手们开始破坏小飞家里有价值的东西，
将小飞本飞从屋里拖了出来，吊在数上，任凭小飞的呼救和扑腾。在两个耳光打的小飞眼冒金星后，晋大公子将
小飞吊在了树上，双脚离地，嘴角流出的血滴滴的落在自己雪白的裙子上。 在阳光的放射下，白的发透，红的发亮。
晋大公子也慢慢的打开了自己带过来的一个刑具盒子，这可是祖上百试不爽的对待不守妇道的人的宝贝。
一件件的刀具即便被磨的铮亮，但是厚重的铁质在深黑的刀具背面透出阵阵寒意，
它们已经很久没有被温润的血喂养了。祖先的选择，你肯定是活不了了，不要怪我哟。

* 漂亮公子篇：：： 
顺着声声惨叫传出，城里的公子哥们懵里，彻底的懵了，他们内心的确是想羞辱这个曾经的辉煌家族。
但是不是说要你死我活的程度。和晋大公子明里暗里的较劲是为了从老爸老妈那里多掏点油水。
我们也明暗里暗里和晋大公子有过交流，好事坏事也一起也干过。加上你晋大公子本身有些行为也不干净，
这种合作和斗争的平衡是大家表面的体面罢了。

现在没地说了，我漂亮公子勾引你以前的相好小飞，而侮辱了你晋大公子，你晋大公子辱回来啊。
唉，你没能力来找我，我的一群老相好你漂亮公子动不了，你却在镇上鞭打你以前的相好。
我漂亮公子想在床上鞭她，你晋大公子却在树上鞭她，我漂亮公子是不道德，但是你晋大公子是在犯罪啊。

都21世纪30年代了，还用家法？我漂亮公子也用过粗，也教训过一些不服气的。
但是我编的理由比你的这个封建权威收到挑战的理由高了很多吧？
我对以前的动过的粗，我不想多说，你要觉得也是犯罪，那你晋大公子可以到城里告我嘛，
能不能成功告到我先不说，至少是个文明的方式啊。
自从我漂亮公子最近生财有道后，我认为人还是得向越文明的地方靠拢， 以保障我生的财安全的再生财，
所以我坚决反对再有粗暴的动武行为。现在人人有手机，谁都能发声，现在还打人，你晋大公子这是绝对的野蛮啊。
我们城里的人都来了，劝你立刻放下手里的武器，退出小飞的家。什么你不退？
我先看看你在城里的存款有多少，冻结一下， 吃个利息先！

鸟小飞复漂亮公子篇：：：
嘿，嘿，你干嘛，啊，啊， 好疼啊，你两米的皮鞭还带刺的，那个缺德的发明的这个刑具， 疼死我啦？
拿刀的那个，想想你在干嘛？你可是在犯罪啊！！警告你一次，警告你两次次，警告你三次，啊，好疼啊，
你割到我血管了！！
Ok,我在疼痛中想了一下，我觉得漂亮公子也靠不住，他说的城里的司法警察会管的嘛，我都叫了几个小时了，
早该到了啊，哦， 哦， 我看到你们了，漂亮公子，快来救我啊！! 我疼的不行了， 你就在我家院外的土包上，
我看到你了， 那个望远镜的就是你，快来啊！你怕他晋大公子干啥啊，你不是给我吹过，说你打十个姓晋的没问题吗？
漂亮公子： 打十个当然没问题啦， 但是现在不是只有一个嘛，我下不去手啊，
          再说了，把姓晋的摁到后他真的会咬人的，没被他咬过，但是看到过他咬啊，我也害怕啊。
          等等啊，我们商量一下，怎么编个大网，困死姓晋的。

鸟小飞：困死姓晋的，你脑子还在不在啊？我流血快死了，你却要我等你们一起饿姓晋的，我跟姓晋的是
         撕破脸了，他现在是就要我死，然后玩弄我的身体，漂亮公子，你要快，也给我带刺的鞭子，
                  我要在树爬上树去抽死这个姓晋的。一个祖宗，这他妈的执行起这该死的家来，下手可是真恨啊。
                  快，漂亮公子，扔个鞭子给我

漂亮公子：人死了还玩个屁啊，老晋啊，别打了，人死了再睡真不好玩，整晚凉嗖嗖，经验之谈，听一句劝啊。
                     亲爱的小飞坚持住啊，我这就给你扎个鞭子仍给你。

* 日月神教篇：：：
本来我日月神教本来就是广发的发动群众的模式，照里说，小飞可以是我教里的一位新发展的对象的。我关注她很久了。这小妞人见人爱，我怎么能不爱啊， 奈何她背景的确不简单，这才双方也就能尽个基本的礼数。我也知道
小飞在找新男朋友，看缘分的事。但是现在美人受苦，我心焉能不疼，我前几天就看事情不对，送了顶帽子给小飞，
先不要管帽子颜色，现在看来，帽子都被抽变形了，心疼啊，帽子。

我首先谴责下你这姓晋的，
在我日月神教的群众组织壮大的今天的规模，不容易啊！你姓晋的也来我这里看过，我们交流通畅，本有大把合作的机会。大丈夫何患无妻，小飞她想飞，你就让她飞吧，女大不中留。你也不想想，小飞凭什么要一直跟着你？婚姻爱情在现在早就自由了。你祖上的那一套不管用了。你看我以前的结发妻子，现在一别两宽，各生欢喜。现在各自都发展不错，联系也没断，一时兴起还能约饭看电影的，多好啊。你这样一直管这小飞不是长久之计啊。哪天你发达了，小飞愿意回去找你，我们肯定不拦着，这是基本的人身自由嘛。老晋啊，你的行为的确犯法了。我知道你祖上留了很的好东西，辉煌过。但是所有可能资助你犯法的行为在城里都不能运作了。

鸟小飞复日月篇：：：
平日里去我和这日月也算礼数尽到了，不看僧面看佛面，把这个姓晋的从我身上先拉开行不？城里的法律条文学的
整整的，一到真的遇到不法就收起你的法官锤，你倒是用你的法官锤捶这姓晋的啊，你人多，你怕啥？

日月： 我真怕啊，恨的真怕不要命的啊，你小飞是现在到处溅血，你到时不还得收拾吗？我也先给你编个鞭子，
然后丢给你, 为了你的自由，使劲抽他姓晋的。我和漂亮公子不能亲自进来救你啊， 那不得扩大矛盾生灵图炭吗？
嘿， 美人，接着这鞭啊，还有啊，小心我那帽子。


在小镇的南边有一神秘组织，名叫天地会。最近天地会纵横捭阖，拉动各地方豪强，熟练游走于各方势力，风升水起。

* 天地会

